name: WordPress CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  wordpress-ci:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: phpcs

    - name: Install WordPress Coding Standards
      run: |
        git clone https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
        phpcs --config-set installed_paths wpcs

    - name: Run WordPress Code Standard
      run: |
        phpcs --standard=WordPress .