name: WordPress CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  wordpress-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHPCS 3
        run: |
          composer global require squizlabs/php_codesniffer:^3.13

      - name: Allow Composer plugin
        run: |
          composer config --global allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install WordPress Coding Standards
        run: |
          composer global require dealerdirect/phpcodesniffer-composer-installer
          composer global require wp-coding-standards/wpcs

      - name: Run PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs -n